Class {
	#name : #GtGradCircleLayoutRadiusSignal,
	#superclass : #BeaconSignal,
	#instVars : [
		'element1',
		'element2',
		'angle1',
		'angle2',
		'rx',
		'ry',
		'rCurrent',
		'radius'
	],
	#category : 'GToolkit-BlocGraph-Grad-Signals'
}

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> angle1 [
	^ angle1
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> angle1: anObject [
	angle1 := anObject
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> angle2 [
	^ angle2
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> angle2: anObject [
	angle2 := anObject
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> element1 [
	^ element1
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> element1: anObject [
	element1 := anObject
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> element2 [
	^ element2
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> element2: anObject [
	element2 := anObject
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> rCurrent [
	^ rCurrent
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> rCurrent: anObject [
	rCurrent := anObject
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> radius [
	^ radius
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> radius: anObject [
	radius := anObject
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> rx [
	^ rx
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> rx: anObject [
	rx := anObject
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> ry [
	^ ry
]

{ #category : #accessing }
GtGradCircleLayoutRadiusSignal >> ry: anObject [
	ry := anObject
]
