Class {
	#name : #GtGradTreeVisitor,
	#superclass : #Object,
	#category : #'GToolkit-BlocGraph-Grad-Tree'
}

{ #category : #visiting }
GtGradTreeVisitor >> visitCompositeNode: aTreeNode [
]

{ #category : #visiting }
GtGradTreeVisitor >> visitLeafNode: aTreeNode [
]

{ #category : #visiting }
GtGradTreeVisitor >> visitNode: aTreeNode [
]

{ #category : #visiting }
GtGradTreeVisitor >> visitRootNode: aTreeNode [
]
