Class {
	#name : #GtGradSouthHierarchicalLayoutExamples,
	#superclass : #GtGradHierarchicalLayoutExamples,
	#category : #'GToolkit-BlocGraph-Grad-Examples'
}

{ #category : #examples }
GtGradSouthHierarchicalLayoutExamples >> layout [
	^ GtGradSouthHierarchicalLayout new
]

{ #category : #examples }
GtGradSouthHierarchicalLayoutExamples >> simpleExample [
	<gtExample>
	^ super simpleExample
]

{ #category : #examples }
GtGradSouthHierarchicalLayoutExamples >> simpleExampleDsiconnectedGraph [
	<gtExample>
	^ super simpleExampleDsiconnectedGraph
]

{ #category : #examples }
GtGradSouthHierarchicalLayoutExamples >> simpleExampleIncreasedInterHierarchySpacing [
	<gtExample>
	^ super simpleExampleIncreasedInterHierarchySpacing
]

{ #category : #examples }
GtGradSouthHierarchicalLayoutExamples >> simpleExampleIncreasedInterRanksSpacing [
	<gtExample>
	^ super simpleExampleIncreasedInterRanksSpacing
]

{ #category : #examples }
GtGradSouthHierarchicalLayoutExamples >> simpleExampleIncreasedIntraRankSpacing [
	<gtExample>
	^ super simpleExampleIncreasedIntraRankSpacing
]

{ #category : #examples }
GtGradSouthHierarchicalLayoutExamples >> simpleExampleWhereAllNodesHaveIncomingEdges [
	<gtExample>
	^ super simpleExampleWhereAllNodesHaveIncomingEdges
]
