SystemOrganization addCategory: #'GToolkit-Diagrammer'!
SystemOrganization addCategory: 'GToolkit-Diagrammer-Commands'!
SystemOrganization addCategory: 'GToolkit-Diagrammer-Examples'!
SystemOrganization addCategory: 'GToolkit-Diagrammer-Model'!
SystemOrganization addCategory: 'GToolkit-Diagrammer-Stencils'!
SystemOrganization addCategory: 'GToolkit-Diagrammer-Tools'!
SystemOrganization addCategory: 'GToolkit-Diagrammer-Tools - Selection'!
SystemOrganization addCategory: 'GToolkit-Diagrammer-UI'!
SystemOrganization addCategory: 'GToolkit-Diagrammer-UI-Lists'!
