Class {
	#name : #GtWardleyMapConstants,
	#superclass : #Object,
	#category : #'GToolkit-WardleyMap-Helpers'
}

{ #category : #'api - constants' }
GtWardleyMapConstants class >> minPipelineRelativeWidth [
	"I represent kind of padding in relative coordinates (0, 1)"

	^ 0.15
]

{ #category : #'api - constants' }
GtWardleyMapConstants class >> pipelineRelativeOffset [
	"I represent kind of padding in relative coordinates (0, 1)"

	^ 0.02
]
