Class {
	#name : #GtWardleyMapNodeViewModelPipelineResized,
	#superclass : #Announcement,
	#instVars : [
		'nodeViewModel'
	],
	#category : #'GToolkit-WardleyMap-Events'
}

{ #category : #accessing }
GtWardleyMapNodeViewModelPipelineResized >> nodeViewModel [
	^ nodeViewModel
]

{ #category : #accessing }
GtWardleyMapNodeViewModelPipelineResized >> nodeViewModel: anObject [
	nodeViewModel := anObject
]
