Class {
	#name : #GtWardleyMapNoteDecoratorModelAdded,
	#superclass : #GtWardleyMapNoteModelAnnouncement,
	#instVars : [
		'decoratorModel'
	],
	#category : #'GToolkit-WardleyMap-Events'
}

{ #category : #accessing }
GtWardleyMapNoteDecoratorModelAdded >> decoratorModel [
	^ decoratorModel
]

{ #category : #accessing }
GtWardleyMapNoteDecoratorModelAdded >> decoratorModel: anObject [
	decoratorModel := anObject
]
