Class {
	#name : #GtWardleyMapEdgeLabelModelAnnouncement,
	#superclass : #GtWardleyMapAnnouncement,
	#instVars : [
		'edgeLabelModel'
	],
	#category : #'GToolkit-WardleyMap-Events'
}

{ #category : #accessing }
GtWardleyMapEdgeLabelModelAnnouncement >> edgeLabelModel [
	^ edgeLabelModel
]

{ #category : #accessing }
GtWardleyMapEdgeLabelModelAnnouncement >> edgeLabelModel: anObject [
	edgeLabelModel := anObject
]
