Class {
	#name : #GtWardleyMapNodeViewModelPipelinePipelineResized,
	#superclass : #Announcement,
	#instVars : [
		'nodeViewModel'
	],
	#category : #'GToolkit-WardleyMap-! View models'
}

{ #category : #accessing }
GtWardleyMapNodeViewModelPipelinePipelineResized >> nodeViewModel [
	^ nodeViewModel
]

{ #category : #accessing }
GtWardleyMapNodeViewModelPipelinePipelineResized >> nodeViewModel: anObject [
	nodeViewModel := anObject
]
