Class {
	#name : #GtWardleyMapNodeLabelModelAnnouncement,
	#superclass : #GtWardleyMapAnnouncement,
	#instVars : [
		'nodeLabelModel'
	],
	#category : #'GToolkit-WardleyMap-Events'
}

{ #category : #accessing }
GtWardleyMapNodeLabelModelAnnouncement >> nodeLabelModel [
	^ nodeLabelModel
]

{ #category : #accessing }
GtWardleyMapNodeLabelModelAnnouncement >> nodeLabelModel: anObject [
	nodeLabelModel := anObject
]
