Class {
	#name : #GtWardleyMapDecoratorModelRemoved,
	#superclass : #GtWardleyMapModelAnnouncement,
	#instVars : [
		'decoratorModel'
	],
	#category : #'GToolkit-WardleyMap-Events'
}

{ #category : #accessing }
GtWardleyMapDecoratorModelRemoved >> decoratorModel [
	^ decoratorModel
]

{ #category : #accessing }
GtWardleyMapDecoratorModelRemoved >> decoratorModel: anObject [
	decoratorModel := anObject
]
