Class {
	#name : #GtWardleyMapEvolveLabelModelAnnouncement,
	#superclass : #GtWardleyMapAnnouncement,
	#instVars : [
		'evolveLabelModel'
	],
	#category : #'GToolkit-WardleyMap-Events'
}

{ #category : #accessing }
GtWardleyMapEvolveLabelModelAnnouncement >> evolveLabelModel [
	^ evolveLabelModel
]

{ #category : #accessing }
GtWardleyMapEvolveLabelModelAnnouncement >> evolveLabelModel: anObject [
	evolveLabelModel := anObject
]
