Class {
	#name : #GtWardleyMapEdgeDecoratorModelAdded,
	#superclass : #GtWardleyMapEdgeModelAnnouncement,
	#instVars : [
		'decoratorModel'
	],
	#category : #'GToolkit-WardleyMap-Events'
}

{ #category : #accessing }
GtWardleyMapEdgeDecoratorModelAdded >> decoratorModel [
	^ decoratorModel
]

{ #category : #accessing }
GtWardleyMapEdgeDecoratorModelAdded >> decoratorModel: anObject [
	decoratorModel := anObject
]
