Trait {
	#name : #TGtWardleyMapVisitor,
	#category : #'GToolkit-WardleyMap-Visitor'
}

{ #category : #visiting }
TGtWardleyMapVisitor >> visitWardleyMap: aWardleyMap [
]

{ #category : #visiting }
TGtWardleyMapVisitor >> visitWardleyMapEdge: aWardleyMapEdge [
]

{ #category : #visiting }
TGtWardleyMapVisitor >> visitWardleyMapNode: aWardleyMapNode [
]

{ #category : #visiting }
TGtWardleyMapVisitor >> visitWardleyMapNodeLabel: aWardleyMapNodeLabel [
]

{ #category : #visiting }
TGtWardleyMapVisitor >> visitWardleyMapNote: aWardleyMapNote [
]
