Trait {
	#name : #TGtWardleyMapNodeType,
	#category : #'GToolkit-WardleyMap-Helpers - Node Type'
}

{ #category : #'api - hooks' }
TGtWardleyMapNodeType >> aboutToRemoveFromNode [
	
]

{ #category : #'api - hooks' }
TGtWardleyMapNodeType >> addedToNode [
	
]

{ #category : #'api - testing' }
TGtWardleyMapNodeType >> isEvolveTargetType [
	^ false
]

{ #category : #'api - testing' }
TGtWardleyMapNodeType >> isRegularType [
	^ false
]
