Class {
	#name : #GtPlotterRawLineExamples,
	#superclass : #Object,
	#category : #'GToolkit-Plotter-Example - Charts'
}

{ #category : #accessing }
GtPlotterRawLineExamples >> commits [
	<gtExample>

	^ { 
		(Date year: 2015 month: 10 day: 5) -> 22.
		(Date year: 2015 month: 12 day: 1) -> 9.
		(Date year: 2015 month: 12 day: 15) -> 12.
		(Date year: 2016 month: 3 day: 10) -> 24.
		(Date year: 2016 month: 3 day: 23) -> 8.
		(Date year: 2016 month: 4 day: 7) -> 7.
		(Date year: 2016 month: 4 day: 19) -> 10.
		(Date year: 2016 month: 8 day: 3) -> 31.
		(Date year: 2017 month: 9 day: 15) -> 23.
		(Date year: 2017 month: 10 day: 6) -> 7.
		(Date year: 2017 month: 11 day: 11) -> 9.
		(Date year: 2018 month: 2 day: 28) -> 15
	}
]
